### ISSUE TITLE
Update relative time in notifications

### ISSUE THREAD

**Issue by szimek** [grechut/watchdog#24]
We should either remove it (also good option) or update it from time to time. If we decide to keep it, we could use e.g. https://www.npmjs.com/package/react-timeago.

**Comment by grechut** [comment]
Hmm in Incidents we already do this dynamically.
https://github.com/grechut/watchdog/blob/master/app/components/IncidentListItem.jsx#L9

I think removal of relative time and keeping only absolute time in notifications is enough.

**Comment by grechut** [comment]
@szimek is this still a valid issue ?
I cannot find any relative time in notifications.
I can find only one in incidents, but it's being dynamically displayed based on raw value (so works fine).

```
~/D/C/watchdog (master) ag fromNow
client/components/IncidentListItem.jsx
9:      <span>{moment(incident.triggeredAt).fromNow()}: <b>{incident.message}</b></span>
~/D/C/watchdog (master)
```

```
~/D/C/watchdog (master) ag format
client/actions/media-stream.js
131:  return moment(timestamp).format('HH:mm:ss');
```

**Comment by szimek** [comment]
In incident list we never update the relative time after it's displayed. If you don't have any new incidents, which would cause the whole list to re-render, you'll have the last incident from "a few seconds ago" for hours.

**Comment by grechut** [comment]
Good catch ;)

https://github.com/grechut/watchdog/pull/32/files
